//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int EmpId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Gender { get; set; }
        public Nullable<int> DepId { get; set; }
    
        public virtual tbl_Department tbl_Department { get; set; }
    }
}
